export function setLanguage(value) {
    const language = value;
    if (language === "persian") {
        const language = {
            rtl: true,
            navTitle: "سیستم مدیریت اپیک گیم",
            profile: "مشاهده پروفایل",
            logOut: "خروج",
            epicGameTeam: "تیم اپیک گیم",
            manageTelegram: "مدیریت تلگرام",
            manageChannel: "مدیریت کانال",
            advancedSearch: "جستجو پیشرفته",
            defaultPost: "مشخصات پیش فرض پست",
            defaultPostRegistration: "ثبت مشخصات پیش فرض پست",
            botSetting: "تنظیمات بات",
            botStatus: "وضعیت بات",
            notification: "نوتیفیکیشن",
            sound: "با صدا",
            silent: "بی صدا",
            postCycleTime: "زمان چرخه پست",
            numberOfRegularPost: "تعداد پست عادی",
            numberOfFavouritePost: "تعداد پست برگزیده",
            code: "کد پست",
            content: "متن پست",
            status: "وضعیت",
            posted: "پست شده",
            sold: "فروخته شده",
            registered: "ثبت شده",
            removed: "حذف شده",
            type: "نوع پست",
            favourite: "برگزیده",
            normal: "عادی",
            choose: "انتخاب کنید...",
            creationDate: "تاریخ ایجاد پست",
            lastUpdateDate: "تاریخ اخرین بروز رسانی",
            post: "پست کردن",
            show: "مشاهده",
            history: "تاریخچه",
            showHistory: "نمایش تاریخچه",
            more: "بیشتر",
            silentPosting: "پست کردن بی صدا",
            edit: "ویرایش پست",
            removeFromChannel: "حذف از کانال",
            delete: "حذف پست",
            addPost: "اضافه کردن پست",
            displayPost: "نمایش پست",
            price: "قیمت",
            priceDollar: "قیمت دلار",
            back: "بازگشت",
            search: "جستجو",
            updateDate: "تاریخ بروز رسانی",
            active: "فعال",
            inactive: "غیر فعال",
            title: "عنوان",
            text: "متن",
            add: "اضافه کردن",
            region: "ریجن",
            done: "انجام عملیات",
            tableResult: "موردی یافت نشد",
            writePartOfYourPostContent: "بخشی از متن پست مورد نظر بنویسید ",
            footerText: "تمامی حقوق این سیستم مدیریت محفوظ میباشید",
            notificationSold: "پست با موفقیت به لیست فروخته شده اضافه شد",
            conError: "ارتباط با سرور برقرار نشد",
            svConError: "مشکلی در برقراری با سرور ایجاد شده است",
            partOfThePost: "قسمتی از پست را بنویسید",
            changesSuccessfully: "تغییرات با موفقیت ثبت شد",
            copy: "کپی شد",
            botText: "تنظیمات بات با موفقیت ثبت شد",
            postCycleTimeText: "زمان چرخه پست را وارد کنید",
            normalPostText: "تعداد پست عادی را وارد کنید",
            favouritePostText: "تعداد پست برگزیده را وارد کنید",
            notificationText: "نوع نوتیفیکیشن را انتخاب کنید",
            botStatusText: "وضعیت بات را انتخاب کنید",
            postRegistered: "پست با موفقیت ثبت شد",
            removeText: "پست با موفقیت از کانال حذف شد",
            removeError: "پست فروخته شده را نمیتوان از کانال حذف کرد",
            delError: "پست حذف شده را نمیتوان از کانال حذف کرد",
            postText: "پست با موفقیت پست شد",
            postSoldError: "پست فروخته شده قابل پست کردن نمی باشد",
            postDelError: "پست حذف شده قابل پست کردن نمی باشد",
            delText: "پست با موفقیت حذف شد",
            delSoldError: "پست حذف شده قابل فروش نیست",
        };
        return language;

    } else if (language === "English") {
        const language = {
            rtl: false,
            navTitle: "EpicGame Management",
            profile: "profile",
            logOut: "log out",
            epicGameTeam: "EpicGame team",
            manageTelegram: "manage Telegram",
            manageChannel: "manage channel",
            advancedSearch: "advanced search",
            defaultPost: "default post",
            defaultPostRegistration: "default post registration",
            botSetting: "bot setting",
            botStatus: "bot status",
            notification: "notification",
            sound: "sound",
            silent: "silent",
            postCycleTime: "post cycle time",
            numberOfRegularPost: "regular post",
            numberOfFavouritePost: "favourite post",
            code: "code",
            content: "content",
            status: "status",
            posted: "posted",
            sold: "sold",
            registered: "registered",
            removed: "removed",
            type: "type",
            favourite: "favourite",
            normal: "normal",
            choose: "choose...",
            creationDate: "creation date",
            lastUpdateDate: "last update date",
            post: "post",
            show: "show",
            history: "history",
            showHistory: "show history",
            more: "more",
            silentPosting: "silent posting",
            edit: "edit",
            removeFromChannel: "remove from channel",
            delete: "delete",
            addPost: "add post",
            displayPost: "display post",
            price: "price",
            priceDollar: "price dollar",
            back: "back",
            search: "search",
            updateDate: "update date",
            active: "active",
            inactive: "inactive",
            title: "title",
            text: "text",
            add: "add",
            done: "done",
            writePartOfYourPostContent: "write part of your post content",
            footerText: "All rights reserved",
            tableResult: "there are no results",
            region: "region",
            notificationSold: "The post was sold",
            conError: "No connection to the server",
            svConError: "There is a problem with the server",
            partOfThePost: "Write a part of the post",
            changesSuccessfully: "The changes were successfully",
            copy: "Copied",
            botText: "The bot settings were successfully",
            postCycleTimeText: "Enter the post cycle time",
            normalPostText: "Enter the number of regular posts",
            favouritePostText: "Enter the number of favourite posts",
            notificationText: "Select the notification type",
            botStatusText: "Select the status of the bot",
            postRegistered: "The post was successfully registered",
            removeText: "The post was removed from the channel",
            removeError: "The sold post cannot be removed from the channel",
            delError: "The deleted post cannot be removed from the channel",
            postText: "The post was successfully posted",
            postSoldError: "Sold post cannot be posted",
            postDelError: "Deleted post cannot be posted",
            delText: "The post was successfully deleted",
            delSoldError: "Deleted post cannot be sold",
        };
        return language;
    }
}


