export function setLanguage(value) {
    const language = value;
    if (language === "persian") {
        const language = {
            rtl: true,
            navTitle: "سیستم مدیریت اپیک گیم",
            profile: "مشاهده پروفایل",
            logOut: "خروج",
            epicGameTeam: "تیم اپیک گیم",
            manageTelegram: "مدیریت تلگرام",
            manageChannel: "مدیریت کانال",
            advancedSearch: "جستجو پیشرفته",
            defaultPost: "مشخصات پیش فرض پست",
            defaultPostRegistration: "ثبت مشخصات پیش فرض پست",
            botSetting: "تنظیمات بات",
            botStatus: "وضعیت بات",
            notification: "نوتیفیکیشن",
            sound: "با صدا",
            silent: "بی صدا",
            postCycleTime: "زمان چرخه پست",
            numberOfRegularPost: "تعداد پست عادی",
            numberOfFavouritePost: "تعداد پست برگزیده",
            code: "کد پست",
            content: "متن پست",
            status: "وضعیت",
            posted: "پست شده",
            sold: "فروخته شده",
            registered: "ثبت شده",
            removed: "حذف شده",
            type: "نوع پست",
            favourite: "برگزیده",
            normal: "عادی",
            choose: "انتخاب کنید...",
            creationDate: "تاریخ ایجاد پست",
            lastUpdateDate: "تاریخ اخرین بروز رسانی",
            post: "پست کردن",
            show: "مشاهده",
            history: "تاریخچه",
            showHistory: "نمایش تاریخچه",
            more: "بیشتر",
            silentPosting: "پست کردن بی صدا",
            edit: "ویرایش پست",
            removeFromChannel: "حذف از کانال",
            delete: "حذف پست",
            addPost: "اضافه کردن پست",
            displayPost: "نمایش پست",
            price: "قیمت",
            priceDollar: "قیمت دلار",
            back: "بازگشت",
            search: "جستجو",
            updateDate: "تاریخ بروز رسانی",
            active: "فعال",
            inactive: "غیر فعال",
            title: "عنوان",
            text: "متن",
            add: "اضافه کردن",
            region: "ریجن",
            done: "انجام عملیات",
            tableResult: "موردی یافت نشد",
            writePartOfYourPostContent: "بخشی از متن پست مورد نظر بنویسید ",
            footerText: "تمامی حقوق این سیستم مدیریت محفوظ میباشید",

        };
        return language;

    } else if (language === "English") {
        const language = {
            rtl: false,
            navTitle: "EpicGame Management",
            profile: "profile",
            logOut: "log out",
            epicGameTeam: "EpicGame team",
            manageTelegram: "manage Telegram",
            manageChannel: "manage channel",
            advancedSearch: "advanced search",
            defaultPost: "default post",
            defaultPostRegistration: "default post registration",
            botSetting: "bot setting",
            botStatus: "bot status",
            notification: "notification",
            sound: "sound",
            silent: "silent",
            postCycleTime: "post cycle time",
            numberOfRegularPost: "regular post",
            numberOfFavouritePost: "favourite post",
            code: "code",
            content: "content",
            status: "status",
            posted: "posted",
            sold: "sold",
            registered: "registered",
            removed: "removed",
            type: "type",
            favourite: "favourite",
            normal: "normal",
            choose: "choose...",
            creationDate: "creation date",
            lastUpdateDate: "last update date",
            post: "post",
            show: "show",
            history: "history",
            showHistory: "show history",
            more: "more",
            silentPosting: "silent posting",
            edit: "edit",
            removeFromChannel: "remove from channel",
            delete: "delete",
            addPost: "add post",
            displayPost: "display post",
            price: "price",
            priceDollar: "price dollar",
            back: "back",
            search: "search",
            updateDate: "update date",
            active: "active",
            inactive: "inactive",
            title: "title",
            text: "text",
            add: "add",
            done: "done",
            writePartOfYourPostContent: "write part of your post content",
            footerText: "all rights reserved",
            tableResult: "there are no results",
            region: "region",
        };
        return language;
    }
}


